language: ruby
before_script:
  - chmod +x ./script/cibuild
script: "./script/cibuild"
# cache: bundler
branches:
  only:
  - gh-pages
  - "/pages-(.*)/"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  hipchat:
    rooms:
      secure: Pwj9GvjqkbjUhWugbwYQbBZR2C3z04nJ8CpmShWAZ2CvB0FvIdQDjAF7o+srMLIsJPfDHLjOaTSyaWc7gmCP8YfeY07k5UVeP0ePOzuOOFNxjqBABYmxTv5bUGjEXJdD+c117T/76VngmjH6mB3lSiS3uIjMtxqygWRHK3zVIScF3DNIlw8X3PFrq3ayeanwP8gDINfjeWlU/eQ9+jyuYStX72TPcCrqRUD67rtzBXAwG/rCjXc7lcXSdPTzUrbPvrQUzrr0Hj+ELvuegG27ztUyhTCUt0sHFIKxd8AjDWm5kd7AfhXv8kU25r05uG788gUmhfeNjWRIVLCC03MqWZY+voPBwt9bt/OB0Hj3HCQrzTKVROz7NDPLSqnq6sTDxX2zbU51WbqSgRHj1QloqQD2HZ8QWWFG1wpDzM1uTeGq7ITf71N249vV/r8pAdaEXWsI310JWK4Wn/DR4Mgp9GFZWIpPKPgWEpBHHyLhIRtpstkBl2kQDnM47bIWJU5oGkYowzIlwjNr46WIgj+7nERTxkXGu/tJ7jC9LZLEMcyfdU4jhHjVUlgSnoJ12DeT5OqpQr9+trfjBaGUcMv+onAP484DEEg/VRcm2MR+1CGyPfYRNxDUD3+RhEK1ZU10EQ5HaTAwOdv6m7DZcrwmGQIeXxUngVaeMuC6P3yimIA=
