#!/usr/bin/env bash
set -e # halt script on error

bundle install
bundle exec jekyll build --config _config_test.yml
bundle exec htmlproof ./_site --check-html --ignore-script-embeds --disable-external --url-ignore "#" --file-ignore "/goojs/"
