#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build --config _config_test.yml
bundle exec htmlproof ./_site --check-html --disable-external --ignore_script_embeds --href-ignore "#" --file-ignore "/goocreate/0.15.6/"
